### ISSUE TITLE
image normaliztion

### ISSUE THREAD

**Issue by wangchust** [Magicboomliu/Accelerator-Simple-Template#4]
left_image_data_resized in the training code is normalized to [0, 1] and fed to the vae encoder. However, according to Marigold, the vae encoder accepts data range [-1, -1]. Is this on purpose?

**Comment by Magicboomliu** [comment]
Since they are only the prompt, you can set to -1 to 1, but 0~1 is also Ok, it does not change the result a lot. Actually the inference code in the official repo, the prompt part(rgb latent)'s input is also 0-1

**Comment by wangchust** [comment]
Thanks for your response!
